#!/bin/sh

echo ""
echo "pulling"
echo "_____________________________________"
git pull

echo ""
echo "Bundling"
echo "_____________________________________"
bundle

echo ""
echo "Running db:create"
echo "_____________________________________"
rake db:create

echo ""
echo "Running db:migrate"
echo "_____________________________________"
rake db:migrate

echo ""
echo "Running db:seed"
echo "_____________________________________"
rake db:seed
