#!/bin/sh

echo ""
echo "pulling"
echo "_____________________________________"
git pull

echo ""
echo "Bundling"
echo "_____________________________________"
bundle

echo ""
echo "Running db:migrate"
echo "_____________________________________"
rake db:migrate

echo ""
echo "Running db:test:prepare"
echo "_____________________________________"
rake db:test:prepare

echo ""
echo "Running deployment:run_deploy_tasks"
echo "_____________________________________"
rake deployment:run_deploy_tasks
