#! /bin/bash
#rvm use ruby-1.9.3-p448
tmate -S /var/tmux/liveon new-session -s liveon -n editor -d
tmate -S /var/tmux/liveon send-keys -t liveon 'cd ~/git/onlife' C-m
tmate -S /var/tmux/liveon send-keys -t liveon 'emacs' C-m
tmate -S /var/tmux/liveon new-window -n rspec -t liveon
tmate -S /var/tmux/liveon new-window -n apps -t liveon
tmate -S /var/tmux/liveon split-window -h
tmate -S /var/tmux/liveon split-window -v
tmate -S /var/tmux/liveon select-pane -L
tmate -S /var/tmux/liveon split-window -v -p 66
tmate -S /var/tmux/liveon split-window -v
tmate -S /var/tmux/liveon new-window -n irb -t liveon
tmate -S /var/tmux/liveon new-window -n services -t liveon
tmate -S /var/tmux/liveon split-window -h
tmate -S /var/tmux/liveon split-window -v
tmate -S /var/tmux/liveon new-window -n guard-ngrok -t liveon
tmate -S /var/tmux/liveon split-window -h
tmate -S /var/tmux/liveon send-keys -t liveon:5.1 'rabbitmq-server' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:5.2 'mongod' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:5.3 'cd ~/git/onlife/liveon' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:5.3 'brew service start redis' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:5.3 'clear' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:5.3 'bundle exec resque-web -p 3010 ./config/initializers/resque.rb' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:2 'cd ~/git/onlife/liveon' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:2 'rake daemon:all:restart' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:2 'clear' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:2 'tmate show-messages' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.1 'cd ~/git/onlife/entity_service' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.1 'pullandprepare' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.1 'bundle exec rails s -p 3002' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.2 'cd ~/git/onlife/assessment_service' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.2 'pullandprepare' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.2 'bundle exec rails s -p 3003' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.3 'cd ~/git/onlife/platform_configuration' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.3 'pullandprepare' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.3 'bundle exec rails s -p 3001' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.4 'cd ~/git/onlife/liveon' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.4 'pullandprepare' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.4 'bundle exec rails s' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.5 'cd ~/git/onlife/plyushkin-service' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.5 'pullandprepare' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:3.5 'rackup -p 3005' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:4 'cd ~/git/onlife' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:6.1 'cd ~/git/onlife/liveon' C-m

tmate -S /var/tmux/liveon send-keys -t liveon:6.2 'cd ~/git/onlife/liveon' C-m
tmate -S /var/tmux/liveon send-keys -t liveon:6.2 'ngrok start liveon onlife' C-m
tmate -S /var/tmux/liveon rename-window -t liveon:2 rspec
tmate -S /var/tmux/liveon rename-window -t liveon:3 apps
tmate -S /var/tmux/liveon rename-window -t liveon:4 irb
tmate -S /var/tmux/liveon rename-window -t liveon:5 services
tmate -S /var/tmux/liveon select-window -t liveon:1
tmate -S /var/tmux/liveon select-window -t liveon:6 guard-ngrok
chgrp tmuxers /var/tmux/liveon
tmate -S /var/tmux/liveon -2 attach -t liveon
