#! /bin/bash
#rvm use ruby-1.9.3-p448
tmux -S /var/tmux/liveon new-session -s liveon -n editor -d
tmux -S /var/tmux/liveon send-keys -t liveon 'cd ~/git/onlife' C-m
tmux -S /var/tmux/liveon send-keys -t liveon 'emacs' C-m
tmux -S /var/tmux/liveon new-window -n rspec -t liveon
tmux -S /var/tmux/liveon new-window -n apps -t liveon
tmux -S /var/tmux/liveon split-window -h
tmux -S /var/tmux/liveon split-window -v
tmux -S /var/tmux/liveon select-pane -L
tmux -S /var/tmux/liveon split-window -v -p 66
tmux -S /var/tmux/liveon split-window -v
tmux -S /var/tmux/liveon new-window -n irb -t liveon
tmux -S /var/tmux/liveon split-window -h
tmux -S /var/tmux/liveon split-window -v
tmux -S /var/tmux/liveon select-pane -L
tmux -S /var/tmux/liveon split-window -v -p 66
tmux -S /var/tmux/liveon split-window -v
tmux -S /var/tmux/liveon new-window -n services -t liveon
tmux -S /var/tmux/liveon split-window -h
tmux -S /var/tmux/liveon new-window -n console -t liveon
tmux -S /var/tmux/liveon send-keys -t liveon:5.1 'sudo rabbitmq-server' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:5.2 'sudo mongod' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:2 'cd ~/git/onlife/liveon' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.1 'cd ~/git/onlife/entity_service' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.1 'bundle exec rails s -p 3002' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.2 'cd ~/git/onlife/assessment_service' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.2 'bundle exec rails s -p 3003' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.3 'cd ~/git/onlife/platform_configuration' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.3 'bundle exec rails s -p 3001' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.4 'cd ~/git/onlife/liveon' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.4 'bundle exec rails s' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.5 'cd ~/git/onlife/onlife_health' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:3.5 'bundle exec rails s -p 9494' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:4 'cd ~/git'
tmux -S /var/tmux/liveon send-keys -t liveon:4 'rails c' C-m
tmux -S /var/tmux/liveon send-keys -t liveon:6 'cd ~/git' C-m
tmux -S /var/tmux/liveon rename-window -t liveon:2 rspec
tmux -S /var/tmux/liveon rename-window -t liveon:3 apps
tmux -S /var/tmux/liveon rename-window -t liveon:4 irb
tmux -S /var/tmux/liveon rename-window -t liveon:5 services
tmux -S /var/tmux/liveon select-window -t liveon:1
chgrp tmuxers /var/tmux/liveon
tmux -S /var/tmux/liveon -2 attach -t liveon
